### ISSUE TITLE
maxline

### ISSUE THREAD

**Issue by frkcn** [19ceng/ceng201pro#17]
####  Soru:

Kullanıcının `MAXLINE=8` iken yeni satır karakteri gelinceye kadar kullanıcıdan aldığı verileri ekrana yazdıran program.
- **Not:** Bu Programı kullanıcı aşırı uzun bir satır yazdığında `MAXLINE` da sonraki kısımları yeni satırdan itibaren güncelle.
##### Çıktı:
- `>>merhaba dunya MAXLINE=3`
- `mer`
- `hab`
- `a d`
- `uny`
- `a`

**Comment by sayz** [comment]
```
#include<stdio.h>
#include<string.h>
#define MAX 3
int main( void )
{
char cumle[40];
int i;
printf( "Cümle giriniz> ");
gets( cumle );
printf( "Girdiğiniz cümle:\n" );
for (i = 0; i<strlen(cumle); i++) {
    if (i%MAX == 0 && i != 0)
        printf("\n");
    else
        printf("%c",cumle[i]);
}
return 0;
}
```

**Comment by ghost** [comment]
for (i = 0; i<strlen(cumle); i++) {
    if (i%MAX == 0 && i != 0)
        printf("\n%c",cumle[i]);

```
else
    printf("%c",cumle[i]);
```

for döngüsünde 3'e tam bölünen karakteri yazmıyordu bu haliyle programın eksiğini gidermeye çalıştık.
