### ISSUE TITLE
strrlc

### ISSUE THREAD

**Issue by frkcn** [19ceng/ceng201pro#6]
#### soru

Herhangi bir dizgi içerisinde `ceng` **var mıdır? yok mudur?** ayırt edebilen programı yazınız.
##### çıktı
- Seçenek 1: `a x cengkleng` --> `Evet`
- Seçenek 2: `a x cenkgleng` --> `Hayır`

**Comment by sayz** [comment]
sorulan soru ile verilen örnek arasında sanki tutarsızlık var gibi? `cengleng` dizgisinde ardarda `ceng` yok ki! sadece bir tane `ceng` geçiyor.

**Comment by seyyah** [comment]
"ardarda" fazlalıktı çıkarıldı.
